config/routes.rb
Rails.application.routes.draw do
 
  
  resources :trains do
    resources :cities
  end

  devise_for :users

  devise_scope :user do
    
    root to: "devise/sessions#new"
    
  end

end

app/models/city.rb
class City < ActiveRecord::Base
belongs_to :train

end

app/models/train.rb
class Train < ActiveRecord::Base
	has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  def after_sign_in_path_for(user)
  	if user.email.equal? "komal.kamble099@gmail.com"
  		trains_path
  	else
  		# Update redirect after creation of user screen
  		logger.debug "------------"
  	    trains_path
  	end
  	
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    logger.debug "********************"
    @train = Train.find(params[:train_id])
    logger.debug "********************************"
    @cities = @train.cities
    logger.debug "cities::: #{@cities}"
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    logger.debug "train #{params} params"
    @train = Train.find(params[:train_id])
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)
    @train = Train.find(params[:train_id])
    respond_to do |format|
      if @city.save
        format.html { redirect_to train_cities_path(@train), notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:arrival_station, :departure_station)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to train_cities_path(@train), notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:name, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/cities/_form.html.erb
<%= form_for [ @train, @city ] do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :arrival_station %><br>
    <%= f.text_field :arrival_station %>
  </div>
  <div class="field">
    <%= f.label :departure_station %><br>
    <%= f.text_field :departure_station %>
  </div>
  <div class="field">
    <%= f.label :arrival_day %><br>
    <%= f.text_field :arrival_day %>
  </div>
  <div class="field">
    <%= f.label :arrival_time %><br>
    <%= f.time_field :arrival_time %>
  </div>
  <div class="field">
    <%= f.label :departure_day %><br>
    <%= f.text_field :departure_day %>
  </div>
  <div class="field">
    <%= f.label :departure_time %><br>
    <%= f.text_field :departure_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cities</h1>

<table>
  <thead>
    <tr>
      <th>Arrival station</th>
      <th>Departure station</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.arrival_station %></td>
        <td><%= city.departure_station %></td>
        <td><%= link_to 'Show', train_city() %></td>
        <td><%= link_to 'Edit', edit_train_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_train_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form' %>

<%= link_to 'Back', train_cities_path(@train) %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Arrival station:</strong>
  <%= @city.arrival_station %>
</p>

<p>
  <strong>Departure station:</strong>
  <%= @city.departure_station %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripPlanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<div class="row">
	<!--div class="col-lg-12 col-md-12 col-xs-12">
		<p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
	</div-->
	<div class="col-lg-12 col-md-12 col-xs-12">
		<%= yield %>
	</div>
</div>
</div>

</body>
</html>

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name , class: "form-control" %>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number , class: "form-control"%>
  </div>
  </div>
  <div class="actions">
    <%= f.submit  class: "btn btn-primary"%>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form' %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12">
    <p id="notice"><%= notice %></p>

    <div class="panel panel-default">
      <div class="panel-heading">
        Listing Trains
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-stripped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Number</th>
                <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
              <% @trains.each do |train| %>
              <tr>
                <td><%= train.name %></td>
                <td><%= train.number %></td>
                <td><%= link_to 'Show', train %></td>
                <td><%= link_to 'Edit', edit_train_path(train) %></td>
                <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>

          <br>

          <%= link_to 'New Train', new_train_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trains/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h1>New Train</h1>
		<%= render 'form' %>

		<%= link_to 'Back', trains_path %>

	</div>
</div>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @train.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>